"""Ajuste na lista de pedidos

Revision ID: 27d9051637b7
Revises: aa65246e9a48
Create Date: 2025-05-26 20:51:34.293168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d9051637b7'
down_revision: Union[str, None] = 'aa65246e9a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_pedidos', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_pedidos', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
