"""alteracao campo client, adicao nome

Revision ID: 9b5bb749a080
Revises: 5a098d07e777
Create Date: 2025-05-25 19:28:03.659618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5bb749a080'
down_revision: Union[str, None] = '5a098d07e777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('nome', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'nome')
    # ### end Alembic commands ###
