"""alteração no valor

Revision ID: aa65246e9a48
Revises: 1252b641855e
Create Date: 2025-05-26 20:33:23.589858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa65246e9a48'
down_revision: Union[str, None] = '1252b641855e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedidos', sa.Column('quantidade', sa.Integer(), nullable=False))
    op.add_column('itens_pedidos', sa.Column('preco', sa.Float(), nullable=False))
    op.drop_column('itens_pedidos', 'price')
    op.drop_column('itens_pedidos', 'quantity')
    op.add_column('pedidos', sa.Column('preco_total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'preco_total')
    op.add_column('itens_pedidos', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('itens_pedidos', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('itens_pedidos', 'preco')
    op.drop_column('itens_pedidos', 'quantidade')
    # ### end Alembic commands ###
