"""ajuste na tabela de produtos

Revision ID: f0d31e11c90e
Revises: d5f5606d2869
Create Date: 2025-05-26 00:04:55.028097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d31e11c90e'
down_revision: Union[str, None] = 'd5f5606d2869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'valor_venda')
    op.drop_column('produtos', 'secao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('secao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('valor_venda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
